name: CI
on:
  workflow_dispatch: {}
  pull_request: {}
  push:
    branches:
      - main
      - master
      paths:
        - .github/workflows/CI.yml

name: Semgrep
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: returntocorp/semgrep-action@v1

      - name: Testing code
        run: |
          semgrep ci
