on:
  workflow_dispatch: {}
  pull_request: {}
  push:
    branches:
      - main
      - master
    paths:
      - .github/workflows/semgrep.yml
  schedule:
    - cron: 14 2 * * *

jobs:
  Testing-unit:
    name: Testing Code
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checking Repository
        uses: actions/checkout@v4

      - name: Checking Setup python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Checking Depedencies with trivy
        uses: aquasecurity/trivy-action@0.31.0
        continue-on-error: true
        with:
          scan-type: fs
          input: .

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Tests with Pytest
        id: pytest-step
        continue-on-error: true
        run: |
          pip install pytest
          pytest app.py

      - name: Run Flask app in background
        run: |
          nohup python app.py &
          sleep 10

  SAST:
    name: semgrep
    runs-on: ubuntu-latest
    permissions:
      contents: read
    container:
      image: semgrep/semgrep

    steps:
      - uses: actions/checkout@v4
      - name: semgrep scan
        run: semgrep --config=auto --json --output semgrep-report.json

      - name: upload semgrep report
        uses: actions/upload-artifact@v4
        with:
          name: semgrep-report
          path: semgrep-report.json
