on:
  workflow_dispatch: {}
  pull_request: {}
  push:
    branches:
      - main
      - master
    paths:
      - .github/workflows/semgrep.yml
  schedule:
    - cron: 14 2 * * *

jobs:
  Testing-unit:
    name: Testing Code
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checking Repository
        uses: actions/checkout@v4

      - name: Checking Setup python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Checking Depedencies with trivy
        uses: aquasecurity/trivy-action@0.31.0
        continue-on-error: true
        with:
          scan-type: fs
          input: .
          format: json
          output: trivy-report.json

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Tests with Pytest
        id: pytest-step
        continue-on-error: true
        run: |
          pip install pytest
          pytest app.py

  SAST:
    name: semgrep
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    container:
      image: semgrep/semgrep

    steps:
      - uses: actions/checkout@v4
      - name: semgrep scan
        run: semgrep --config=auto --sarif --output semgrep-report.sarif

      - name: upload semgrep report
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: semgrep-report.sarif
  DAST:
    name: DAST with Wapiti
    runs-on: windows-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - name: Install Flask and Wapiti
        run: |
          python -m pip install --upgrade pip
          pip install flask wapiti3
      - name: Run Flask app in background
        run: |
          start /b python app.py
          timeout /t 30
        env:
          APP_URL: http://localhost:5000
      - name: Verify Flask app is running
        run: |
          curl --fail ${{ env.APP_URL }} || exit 1
        shell: bash
      - name: Run Wapiti Scan
        run: |
          wapiti -u ${{ env.APP_URL }} -o wapiti-report.json --format json
        shell: powershell
      - name: Upload Wapiti Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: wapiti-report
          path: wapiti-report.json
