on:
  workflow_dispatch: {}
  pull_request: {}
  push:
    branches:
      - main
      - master
    paths:
      - .github/workflows/semgrep.yml
  schedule:
    - cron: 14 2 * * *

jobs:
  Testing-unit:
    name: Testing Code
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checking Repository
        uses: actions/checkout@v4

      - name: Checking Setup python
        uses: actions/setup-python@v5

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest safety
          pip install -r requirements.txt

      - name: Run Tests
        id: pytest-step
        continue-on-error: true
        run: |
          pytest

      - name: Checking Depedencies
        id: safety-step
        continue-on-error: true
        run: |
          safety check

  Testing:
    name: semgrep
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
    container:
      image: semgrep/semgrep

    steps:
      - uses: actions/checkout@v4
      - name: semgrep scan
        run: semgrep --config=auto --json --output semgrep-report.json

      - name: upload semgrep report
        uses: actions/upload-artifact@v4
        with:
          name: semgrep-report
          path: semgrep-report.json
